### ISSUE TITLE
5. Domain Driven Design

### ISSUE THREAD

**Issue by michal-murawski-90poe** [boxgames1/frontend-challenge-github-react#5]
There is a lot covered in the app, which is very lovely! 

I wanted to ask about moving pieces around to match the modular approach. How would you structure it? Some inspiration here: https://alexmngn.medium.com/why-react-developers-should-modularize-their-applications-d26d381854c1

If you disagree with this approach or believe the app is modular enough already, feel free to argument💪

**Comment by boxgames1** [comment]
Nice one!

I love DDD, it's an approach I used in the past, and also wrote about adapting it to functional programming (https://medium.com/itnext/ddd-in-node-typescript-the-functional-way-part-1-98d18d998b33 - I should finish the series someday 🤦 )

In the frontend, it doesn't fit as well as in the backend. In the UI we tend to share much more components, and structure projects in different ways.

So it really depends on which are the requirements and the agreement with the team. If DDD is the decided approach in the frontend, I'd extract common parts to a separate folder (as I do now), and then I would keep modules/domains encapsulated in their own folders.

**Comment by michal-murawski-90poe** [comment]
Thanks for a response! Good input :) I agree, front-end is harder to keep in the pure DDD style, because of its nature.

I will check the art later, kudos!
