### ISSUE TITLE
6. DX tools

### ISSUE THREAD

**Issue by michal-murawski-90poe** [boxgames1/frontend-challenge-github-react#6]
There are a few small pieces that need to be included for a perfect **DX**.

 Could you add the following:
- **prettier**,
- **git-hooks**, which would fire scripts on staged files only,
- [codegen tool](https://www.the-guild.dev/graphql/codegen) for auto hooks&types generation and use them in the codebase.

This is the last issue, I promise! The task in its current state is very well delivered. These few issues are here to improve the score and test out our communication 🖖

**Comment by boxgames1** [comment]
Added!

Never used codegen, but seems to be a nice tool :)
